01 let i = 7
02 if i < 10 then print "0", i, " blah" : if i >= 10 then print i, " oijiojiojo"
03 let i = i + 1
04 if i < 100 then goto 02
05 end

06 i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i
07 blah
08 blah
09 blah
10 oijiojiojo
11 oijiojiojo
12 oijiojiojo
13 oijiojiojo
14 oijiojiojo
15 oijiojiojo
16 oijiojiojo
17 oijiojiojo
18 oijiojiojo
19 oijiojiojo
20 oijiojiojo
21 oijiojiojo
22 oijiojiojo
23 oijiojiojo
24 oijiojiojo
25 oijiojiojo
26 oijiojiojo
27 oijiojiojo
28 oijiojiojo
29 oijiojiojo
30 oijiojiojo
31 oijiojiojo
32 oijiojiojo
33 oijiojiojo
34 oijiojiojo
35 oijiojiojo
36 oijiojiojo
37 oijiojiojo
38 oijiojiojo
39 oijiojiojo
40 oijiojiojo
41 oijiojiojo
42 oijiojiojo
43 oijiojiojo
44 oijiojiojo
45 oijiojiojo
46 oijiojiojo
47 oijiojiojo
48 oijiojiojo
49 oijiojiojo
50 oijiojiojo
51 oijiojiojo
52 oijiojiojo
53 oijiojiojo
54 oijiojiojo
55 oijiojiojo
56 oijiojiojo
57 oijiojiojo
58 oijiojiojo
59 oijiojiojo
60 oijiojiojo
61 oijiojiojo
62 oijiojiojo
63 oijiojiojo
64 oijiojiojo
65 oijiojiojo
66 oijiojiojo
67 oijiojiojo
68 oijiojiojo
69 oijiojiojo
70 oijiojiojo
71 oijiojiojo
72 oijiojiojo
73 oijiojiojo
74 oijiojiojo
75 oijiojiojo
76 oijiojiojo
77 oijiojiojo
78 oijiojiojo
79 oijiojiojo
80 oijiojiojo
81 oijiojiojo
82 oijiojiojo
83 oijiojiojo
84 oijiojiojo
85 oijiojiojo
86 oijiojiojo
87 oijiojiojo
88 oijiojiojo
89 oijiojiojo
90 oijiojiojo
91 oijiojiojo
92 oijiojiojo
93 oijiojiojo
94 oijiojiojo
95 oijiojiojo
96 oijiojiojo
97 oijiojiojo
98 oijiojiojo
99 oijiojiojo
